---
- name: This sets up an app server
  hosts: app-server
  become: yes
  tasks:
  - name: Ensure Java is installed.
    package:
      name: "java-1.8.0-openjdk"
      state: present
    
  - name: tomcat | group add
    group: name=tomcat

  - name: tomcat | user add
    user: name=tomcat group=tomcat home=/opt/tomcat8 createhome=no  

  - name: Test if TOMCAT binary has already been downloaded.
    stat:
      path: /tmp/apache-tomcat-8.5.40.tar.gz
    register: binary

  - name: tomcat | binary download
    get_url: 
      url: "http://mirror.nus.edu.sg/apache/tomcat/tomcat-8/v8.5.40/bin/apache-tomcat-8.5.40.tar.gz"
      dest: "/tmp"
      timeout: 300
    when: binary.stat.exists == False

  - name: tomcat  | extract archive
    shell: "tar xzf /tmp/apache-tomcat-8.5.40.tar.gz -C /opt"

  - name: tomcat  | symlink install directory
    file: src="/opt/apache-tomcat-8.5.40" path="/opt/tomcat8" state=link
    
  - name: tomcat  |   change ownership of target installation
    file: path="/opt/tomcat8" owner=tomcat group=tomcat state=directory recurse=yes

  - name: tomcat  | systemd
    template: src=tomcat.service.j2 dest=/etc/systemd/system/tomcat.service
  
  - name: tomcat  | restart
    service:
      name: tomcat
      state: restarted