apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  namespace: apps-dev
spec:
  containers:
  - name: nginx
    image: henryl39/nginx:firsttry
    command:
    - /usr/sbin/nginx
    - -g
    - daemon off;
    - -q
    imagePullPolicy: Always
    ports:
    - containerPort: 80

  - name: go
    image: henryl39/go:firsttry
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
    livenessProbe:
      exec:
        command:
        - cat
        - /go/bin/test 
      initialDelaySeconds: 10
      periodSeconds: 5
    readinessProbe:
      exec:
        command:
        - cat
        - /go/bin/test
      initialDelaySeconds: 15
      periodSeconds: 5

  imagePullSecrets:
  - name: regcred