---
- name: This deploy app sample.war to TOMCAT
  hosts: app-server
  become: yes
  tasks:
  - name: Ensure tomcat service is running
    service:
      name: "tomcat"
      state: started
      
  - name:  application archive sample.war in webapps directory
    copy:
      src: sample.war
      dest: /opt/tomcat8/webapps
      owner: tomcat
      group: tomcat
      mode: u=rwx,g=rx,o=r

  - name: Ensure application is deployed
    stat: 
      path: /opt/tomcat8/webapps/sample

  - name: Check that you can connect (GET) to a sample app welcome page and it returns a status 200 before continue
    uri:
      url: http://localhost:8080/sample/index.html
    register: result
    until: result.status == 200
    retries: 10
    delay: 10

  - name : Affiche la variable result
    debug:
      var: result
  
